FROM python:3.11-slim-buster


# Set environment variables to minimize interactive prompts
ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1

# Install necessary dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    libfontconfig1 \
    libfreetype6 \
    libx11-6 \
    libxrender1 \
    libxext6 \
    libxcb1 \
    libuuid1 \
    && rm -rf /var/lib/apt/lists/*


RUN apt-get update && apt-get install -y --no-install-recommends \
    ttf-mscorefonts-installer \
    fonts-dejavu \
    && fc-cache -f -v \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application
COPY . .

RUN rm -rf .venv & python3 -m venv .venv & source .venv/bin/activate \
    & pip install --upgrade pip & pip install -r ./requirements.txt \ 
    & black metavox tests & pylint --fail-under=9.9 metavox tests \
    & pytest --ignore=tests/benchmark --ignore=tests/audio --cov-fail-under=95 --cov metavox -v tests