FROM python:3.11-slim-buster


RUN apt install wget \
    & wget -q https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    & dpkg -i packages-microsoft-prod.deb \
    & apt-get update \
    & apt-get install apt-transport-https \
    & apt-get update \
    & apt-get install dotnet-sdk-3.1

# Set the working directory
WORKDIR /app

# Copy requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application
COPY . .

RUN rm -rf .venv & python3 -m venv .venv & source .venv/bin/activate \
    & pip install --upgrade pip & pip install -r ./requirements.txt \ 
    & black metavox tests & pylint --fail-under=9.9 metavox tests \
    & pytest --ignore=tests/benchmark --ignore=tests/audio --cov-fail-under=95 --cov metavox -v tests